### ISSUE TITLE
Could you help me setup a header for my cards?

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [hgiesel/anki_script_manager#13]
Hi,

Your addon seems incredible but I can't make it work. I am somewhat a python coder but lacks understanding of how js and html interact with anki and it's definitely my fault for not understanding how to use it. I think your project would benefit a lot from a small tutorial and my use case could make for a good example.

My use case : I would simply like to add a header to my cards. Currently I have to edit them by hand every time I make a modification etc and it's quite annoying.

Here's the current header :

`<div class = smallFontHeader><span class=grey>Deck - {{clickable:Deck}} {{#Tags}} |      Tags - {{clickable:Tags}}{{/Tags}} </span><span class = notOnMobile > | <u><span class=red>{{info-New?:}}</span>{{info-Review?:}}{{info-Learning?:}}</u> | Ease = {{info-Factor:}}</div>`

Would you mind walking me through the process of adding this header to all my note types? I think then linking to this issue on ankiweb would help other to make sense of your addon for people that are not *that* confortable with js.

Have a nice day!

**Comment by hgiesel** [comment]
So let me get this straight, you want to add it to all of your **note types**, not **card types**? I'm just making sure, because even I confuse the terminology sometimes.

Asset Manager works _per note type_, so if it were *note types*, you'd still have to change it for each note type.

Otherwise, I'd suggest you send me the note type (by exporting a deck with at least one card of this note type, can also be a dummy card).

I'd then have a look at the note type(s) and demonstrate it to you directly on them.

**Comment by thiswillbeyourgithub** [comment]
Hi, thanks for answering so quickly. I'm not sure I understand what you mean by card vs notes. What I meants was adding a header to my clozes types and my image occlusions, basics etc.

So what should I do?

**Comment by hgiesel** [comment]
I'm sorry, at some point I forgot about this issue. I think what you'd need is #23. Closing this as impossible at the moment.
